[package]
description="rapid string matching library"
name = "rapidfuzz"
version = "0.2.0"
authors = ["maxbachmann"]
edition = "2018"
readme = "Readme.md"
license = "MIT"
maintenance = { status = "actively-developed" }


[lib]
name = "rapidfuzz"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rand = "0.8.5"
strsim = "0.10.0"

[[bench]]
name = "benches"
harness = false